"""This python code considers LISTS,TURPLES AND DICTIONARIES.They are used to enter a series of items in our program
and are either displayed or worked on"""

# 1-LISTS-They help produce a series of items which can be manipulated on the user need
EPL_TEAMS=["manchester united ","manchester city","chelsea","arsenal","tottenham"]
print(EPL_TEAMS)
EPL_TEAMS.append("wolves")
print(EPL_TEAMS)


# 2-TURPLES-THEY CAN NOT BR MANIPULATED OR EDITED
UNITEDSTATESOFAFRICA=("kenya","tanzania","uganda","rwanda","burundi","congo","ethiopia","southsudan")
print("This are the countries that am gonna focus on improving with my invention and innovations",UNITEDSTATESOFAFRICA )


# 3-DICTIONARIES-THEY ARE USED TO STORE A COLLECTION OF DATA PAIRS I.e password or in normal terms as the usual dictionary
passwords={"code":1234,"kartel":4567,"victor":345,"mwangi":4567}
print(passwords)
#you can delete update and do other manipulations in dictionaries










